package Visao;

import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Windows 7
 */
public class JFRMTemplateManter extends javax.swing.JFrame {

    /**
     * Creates new form JFRMTemplate
     */
    public JFRMTemplateManter() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPNLNorte = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTBBuscaRapida = new javax.swing.JTable();
        jBTCadastrar = new javax.swing.JButton();
        jBTConfirmar = new javax.swing.JButton();
        jBTCancelar = new javax.swing.JButton();
        jBTAlterar = new javax.swing.JButton();
        jBTSalvar = new javax.swing.JButton();
        jBTExcluir = new javax.swing.JButton();
        jBTNBuscar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPNLNorte.setPreferredSize(new java.awt.Dimension(600, 270));

        jTBBuscaRapida.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTBBuscaRapida.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
//                jTBBuscaRapidaMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTBBuscaRapida);

        jBTCadastrar.setText("Cadastrar");
        jBTCadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jBTCadastrarActionPerformed(evt);
            }
        });

        jBTConfirmar.setText("Confirmar");
        jBTConfirmar.setEnabled(false);
        jBTConfirmar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jBTConfirmarActionPerformed(evt);
            }
        });

        jBTCancelar.setText("Cancelar");
        jBTCancelar.setEnabled(false);
        jBTCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jBTCancelarActionPerformed(evt);
            }
        });

        jBTAlterar.setText("Alterar");
        jBTAlterar.setEnabled(false);
        jBTAlterar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jBTAlterarActionPerformed(evt);
            }
        });

        jBTSalvar.setText("Salvar");
        jBTSalvar.setEnabled(false);
        jBTSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jBTSalvarActionPerformed(evt);
            }
        });

        jBTExcluir.setText("Excluir");
        jBTExcluir.setEnabled(false);
        jBTExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jBTExcluirActionPerformed(evt);
            }
        });

        jBTNBuscar.setText("Atualizar");
        jBTNBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
//                jBTNBuscarActionPerformed(evt);
            }
        });

        jLabel1.setText("Selecione uma linha para ALTERAR");

        javax.swing.GroupLayout jPNLNorteLayout = new javax.swing.GroupLayout(jPNLNorte);
        jPNLNorte.setLayout(jPNLNorteLayout);
        jPNLNorteLayout.setHorizontalGroup(
            jPNLNorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPNLNorteLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPNLNorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPNLNorteLayout.createSequentialGroup()
                        .addComponent(jBTCadastrar)
                        .addGap(22, 22, 22)
                        .addComponent(jBTConfirmar)
                        .addGap(26, 26, 26)
                        .addComponent(jBTCancelar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 120, Short.MAX_VALUE)
                        .addComponent(jBTAlterar)
                        .addGap(18, 18, 18)
                        .addComponent(jBTSalvar)
                        .addGap(18, 18, 18)
                        .addComponent(jBTExcluir))
                    .addComponent(jBTNBuscar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
            .addGroup(jPNLNorteLayout.createSequentialGroup()
                .addGap(229, 229, 229)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPNLNorteLayout.setVerticalGroup(
            jPNLNorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPNLNorteLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jBTNBuscar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 16, Short.MAX_VALUE)
                .addGroup(jPNLNorteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBTExcluir)
                    .addComponent(jBTSalvar)
                    .addComponent(jBTAlterar)
                    .addComponent(jBTCadastrar)
                    .addComponent(jBTConfirmar)
                    .addComponent(jBTCancelar))
                .addContainerGap())
        );

        getContentPane().add(jPNLNorte, java.awt.BorderLayout.NORTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    protected void jBTExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTExcluirActionPerformed
        int confirmOption = 1;

        confirmOption = JOptionPane.showConfirmDialog(null, "Você realmente deseja excluir estes dados?", "Alerta de exclusão de dados", JOptionPane.YES_NO_OPTION);

        if (confirmOption == 1)
        return;

        this.jBTConfirmar.setEnabled(false);
        this.jBTCadastrar.setEnabled(true);
        this.jBTAlterar.setEnabled(false);
        this.jBTSalvar.setEnabled(false);
        this.jBTExcluir.setEnabled(false);
        this.jBTCancelar.setEnabled(false);
    }//GEN-LAST:event_jBTExcluirActionPerformed

    protected void jBTSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTSalvarActionPerformed
        this.jBTConfirmar.setEnabled(false);
        this.jBTCadastrar.setEnabled(true);
        this.jBTSalvar.setEnabled(false);
        this.jBTAlterar.setEnabled(false);
        this.jBTExcluir.setEnabled(false);
        this.jBTCancelar.setEnabled(false);
    }//GEN-LAST:event_jBTSalvarActionPerformed

    protected void jBTAlterarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTAlterarActionPerformed
        this.jBTConfirmar.setEnabled(false);
        this.jBTCadastrar.setEnabled(false);
        this.jBTSalvar.setEnabled(true);
        this.jBTAlterar.setEnabled(false);
        this.jBTExcluir.setEnabled(false);
        this.jBTCancelar.setEnabled(true);
    }//GEN-LAST:event_jBTAlterarActionPerformed

    protected void jBTCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTCancelarActionPerformed
        this.jBTConfirmar.setEnabled(false);
        this.jBTCadastrar.setEnabled(true);
        this.jBTAlterar.setEnabled(false);
        this.jBTSalvar.setEnabled(false);
        this.jBTExcluir.setEnabled(false);
        this.jBTCancelar.setEnabled(false);
    }//GEN-LAST:event_jBTCancelarActionPerformed

    protected void jBTConfirmarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTConfirmarActionPerformed
        this.jBTConfirmar.setEnabled(false);
        this.jBTCadastrar.setEnabled(true);
        this.jBTAlterar.setEnabled(false);
        this.jBTSalvar.setEnabled(false);
        this.jBTExcluir.setEnabled(false);
        this.jBTCancelar.setEnabled(false);
    }//GEN-LAST:event_jBTConfirmarActionPerformed

    protected void jBTCadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTCadastrarActionPerformed
        this.jBTConfirmar.setEnabled(true);
        this.jBTCadastrar.setEnabled(false);
        this.jBTAlterar.setEnabled(false);
        this.jBTSalvar.setEnabled(false);
        this.jBTExcluir.setEnabled(false);
        this.jBTCancelar.setEnabled(true);
    }//GEN-LAST:event_jBTCadastrarActionPerformed

    protected void jTBBuscaRapidaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTBBuscaRapidaMouseClicked
        this.jBTConfirmar.setEnabled(false);
        this.jBTCadastrar.setEnabled(false);
        this.jBTAlterar.setEnabled(false);
        this.jBTAlterar.setEnabled(true);
        this.jBTExcluir.setEnabled(true);
        this.jBTCancelar.setEnabled(true);
    }//GEN-LAST:event_jTBBuscaRapidaMouseClicked

    protected void jBTNBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBTNBuscarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jBTNBuscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JFRMTemplateManter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JFRMTemplateManter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JFRMTemplateManter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JFRMTemplateManter.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JFRMTemplateManter().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    protected javax.swing.JButton jBTAlterar;
    protected javax.swing.JButton jBTCadastrar;
    protected javax.swing.JButton jBTCancelar;
    protected javax.swing.JButton jBTConfirmar;
    protected javax.swing.JButton jBTExcluir;
    protected javax.swing.JButton jBTNBuscar;
    protected javax.swing.JButton jBTSalvar;
    protected javax.swing.JLabel jLabel1;
    protected javax.swing.JPanel jPNLNorte;
    protected javax.swing.JScrollPane jScrollPane2;
    public javax.swing.JTable jTBBuscaRapida;
    // End of variables declaration//GEN-END:variables
}
